# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-07 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antiques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='')),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_now_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bought', models.BooleanField(default=False)),
                ('edu_info', models.TextField(default='')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
