# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-27 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiques',
            name='date_of_posting',
            field=models.DateField(auto_now=True),
        ),
    ]
