# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-27 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0002_antiques_date_of_posting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antiques',
            name='date_of_posting',
        ),
        migrations.AddField(
            model_name='antiques',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
