# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-31 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0002_auto_20200328_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antiques',
            name='current_bid',
        ),
    ]
