# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-12 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0002_enquire'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquire',
            name='time_requested',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
