# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-12 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0003_enquire_time_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquire',
            name='enquiry',
            field=models.CharField(default='', max_length=999),
        ),
    ]
