# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-02 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0003_remove_antiques_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiques',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
