# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-12 18:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0004_auto_20200412_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquire',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
