# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-31 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='antique_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='antiques.Antiques'),
        ),
    ]
