# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-31 01:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0003_auto_20200331_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='current_leader',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=15),
        ),
        migrations.AddField(
            model_name='auction',
            name='money_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='winning_bidder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=15),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
