# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-31 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20200331_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_amount',
            new_name='new_bid',
        ),
    ]
