# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-04 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auto_20200404_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='id',
        ),
        migrations.AlterField(
            model_name='auction',
            name='antiques',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='antiques.Antiques'),
        ),
    ]
