# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-07 22:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=56)),
                ('lastname', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=45)),
                ('post_code', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
