# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-28 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
