# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-28 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200328_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='externalURL',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='image',
            field=models.ImageField(blank=True, upload_to='settings.MEDIA_ROOT'),
        ),
    ]
