# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-28 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200328_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
