# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-29 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200328_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastsold',
            name='date_sold',
            field=models.DateTimeField(blank=True),
        ),
    ]
