# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-29 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200329_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastsold',
            name='edu_info',
            field=models.CharField(default='', max_length=300),
        ),
    ]
