# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-30 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_pastsold_edu_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrequest',
            name='externalURL',
        ),
    ]
