# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-30 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_itemrequest_externalurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item-request-images'),
        ),
    ]
