# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-31 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200330_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
